[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ailite"
version = "7.0.1"
description = "All popular Framework HF integration kit"
authors = [ "Kammari Santhosh",]
readme = "README.md"
license = "MIT License"
repository = "https://github.com/santhosh/"
keywords = [ "",]
[[tool.poetry.packages]]
include = "ailite"

[tool.poetry.dependencies]
python = "^3.10"
langchain_ollama = "^0.2.2"
wordllama = "^0.3.7"
visionlite = "^0.1.58"
