[tool.poetry]
name = "ailite"
version = "6.0.2"
description = "All popular Framework HF integration kit"
authors = ["Kammari Santhosh"]
readme = "README.md"
license = "MIT License"
repository = "https://github.com/santhosh/"
keywords = [""]
packages = [
    {include = "ailite"}
]
include = [
    "chat_gui.py",
    "chat_run.py"
]

[tool.poetry.dependencies]
python = "^3.10"
dspy="^2.5.41"
litellm="^1.54.0"
ailitellm="^0.1.6"

#[tool.poetry.scripts]
#claude-chat = "chat_gui:run_app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"